### ISSUE TITLE
Doesn't work for projects built with Expo SDK 50

### ISSUE THREAD

**Issue by RohanSensei** [expo/vscode-expo#240]
### Description of the bug
Doesn't work for projects built with Expo SDK 50, always stuck at 'waiting for device to connect...'"

### To Reproduce

1. create a new project: "npx create-expo-app@latest --template tabs@50"
2. run "npx expo start" in vscode terminal, press i or a to start app in IOS or Android
3. run the Debug command, Expo: Debug ...
4. the dialog pop out

#### Expected behavior
dialog box disappear and you can debug in debug console in vscode.

#### Actual behavior
always stuck at 'waiting for device to connect...'"

### Additional context
It works fine with lower expo sdk version projects.

**Comment by EzioLi01** [comment]
Cannot get any ws target info from bundler url from expo50.

**Comment by byCedric** [comment]
Hi all! We had an issue in Expo Go, which we fixed 4 days ago, and released 1-2 days ago (pending store review). If you use a simulator or emulator, make sure you are using the latest Expo Go version (`2.30.9` for both Android and iOS).

If that doesn't work, do let me know!

**Comment by ArnieGA** [comment]
I'm also unable to use the extension on my end. The only action I see if for a progress bar like graphic show and then hide, at the top of VS Code's `Run and Debug` tab. I'm using `Debug: Debug Expo app on a device or simulator, using Hermes` to start the process.

If it helps, here's information about my specific scenario/environment...

### VS Code
```
Version: 1.86.0 (system setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
```
### System installed Node.js:  20.11.0 (NVM managed)
### Expo
- Expo SDK Version: 50.0.0
- Runtime version: exposdk:50.0.0
- Expo Go version (from emulator's `App info` screen): 2.30.9
### Project's `package.json`
```
{
	"name": <private>,
	"version": "1.0.0",
	"main": "./src/index.tsx",
	"scripts": {
		"start": "expo start",
		"start:c": "expo start -c",
		"android": "expo start -c --android",
		"ios": "expo start -c --ios",
		"web": "expo start -c --web"
	},
	"dependencies": {
		"@expo/webpack-config": "^19.0.1",
		"@reduxjs/toolkit": "^2.1.0",
		"@rneui/base": "^4.0.0-rc.7",
		"@rneui/themed": "^4.0.0-rc.8",
		"axios": "^1.6.7",
		"expo": "~50.0.5",
		"expo-crypto": "~12.8.0",
		"expo-router": "~3.4.6",
		"expo-status-bar": "~1.11.1",
		"lodash": "^4.17.21",
		"react": "18.2.0",
		"react-dom": "18.2.0",
		"react-native": "0.73.2",
		"react-native-dotenv": "^3.4.9",
		"react-native-safe-area-context": "4.8.2",
		"react-native-screens": "~3.29.0",
		"react-native-web": "~0.19.10",
		"react-redux": "^9.1.0",
		"text-encoding": "^0.7.0"
	},
	"devDependencies": {
		"@babel/core": "^7.23.9",
		"@types/lodash": "^4.14.202",
		"@types/react": "~18.2.51",
		"typescript": "^5.3.3"
	},
	"private": true
}
```
### Debugging information
At VS Code's `Output` window, selecting the `Window` option at the dropdown shows me the following error message:
```
2024-02-02 07:16:56.679 [error] [Extension Host] Error: Could not connect to debug target at http://localhost:9229: Could not find any debuggable target
    at c:\program files\microsoft vs code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:139:37992
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at n (c:\program files\microsoft vs code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:143:3699)
    at Sd.launch (c:\program files\microsoft vs code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:142:31584)
    at x0.captureLaunch (c:\program files\microsoft vs code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:159:11374)
    at x0._launch (c:\program files\microsoft vs code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:159:11121)
    at async Promise.all (index 5)
    at x0._boot (c:\program files\microsoft vs code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:159:10245)
    at c:\program files\microsoft vs code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:159:9124
    at xl._onMessage (c:\program files\microsoft vs code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:76:4840)
```

**Comment by orenagiv** [comment]
Hey,
Same here...

Any news about this one?

**Comment by RohanSensei** [comment]
seems ok now!

**Comment by nicolasWD** [comment]
Same here, I have a project with Expo SDK 49, my VS Code is v.1.86.1 and Expo Go v.2.30.9

I have tried the command Expo: Debug, and nothing appears on the screen except the "Inspect Expo App" in Call Stack under the Run and Debug section, it appears for 5 seconds and then disappears.

I've tried using the port 9229 as with the users above and I get the same behavior.

Would love to see a solution to this!

**Comment by sebastianrueckerai** [comment]
Same here, after two days of experimenting none of the documented ways of debugging seem to work with the latest SDK version!

**Comment by sebastianrueckerai** [comment]
I opened this related issue and provided a repo with my minimal example: https://github.com/expo/expo/issues/27157#issuecomment-1952506111

**Comment by DeabitTech** [comment]
guys this is a big issue, i'm still have this issue. like your cases i did the upgrade from previous version of expo (45 in my case) to the 50, and i fixed a lot of issues in the meanwhile, but this about the Assets still here. in my case this is the first error i encontering when i launch the run:ios:  node_modules/@expo-google-fonts/nunito/Nunito_500Medium.ttf: Assets must have hashed files. Ensure the expo-asset plugin is installed.

but if i commenting the part of my code about the fonts, i have the same issues but on expo-vectors.

please fix it @expo-bot

**Comment by 0xAskar** [comment]
I also want to add that... after fixing many bugs and module problems after upgrading to expo 50, the app is completely blank with no error. There is completely no error, and its impossible to use the app
<img width="885" alt="image" src="https://github.com/expo/vscode-expo/assets/37524379/3c4ee7c4-92f2-4379-974c-2499e12d6b4e">

**Comment by rsapko** [comment]
I've installed the Expo Tools extension in VSCODE. I can't find the "Exp: Debug ... command anywhere. What am I missing? Working on a MAC.

**Comment by nicolasWD** [comment]
> I've installed the Expo Tools extension in VSCODE. I can't find the "Exp: Debug ... command anywhere. What am I missing? Working on a MAC. I'm wanting to debug with breakpoints in VSCODE.

@rsapko You need to press F1 and search for it in the dropdown box

**Comment by rsapko** [comment]
> > I've installed the Expo Tools extension in VSCODE. I can't find the "Exp: Debug ... command anywhere. What am I missing? Working on a MAC. I'm wanting to debug with breakpoints in VSCODE.
> 
> @rsapko You need to press F1 and search for it in the dropdown box

**Comment by nicolasWD** [comment]
I don't know, the problem for me it seems that the extension is not attaching to the packager and thus, cannot debug any breakpoints either on MAC or PC (I work on both)

**Comment by rsapko** [comment]
> I don't know, the problem for me it seems that the extension is not attaching to the packager and thus, cannot debug any breakpoints either on MAC or PC (I work on both)

Have you been able to find a setup that works with breakpoints in VSCODE? Attaching to Hermes works somewhat, but the source maps seem off and the 'watch' and 'variables' are inconsistent. Can you share a launch.json if you have it working?

**Comment by nicolasWD** [comment]
> > I don't know, the problem for me it seems that the extension is not attaching to the packager and thus, cannot debug any breakpoints either on MAC or PC (I work on both)
> 
> Have you been able to find a setup that works with breakpoints in VSCODE? Attaching to Hermes works somewhat, but the source maps seem off and the 'watch' and 'variables' are inconsistent. Can you share a launch.json if you have it working?

@rsapko I have the React Native Tools extension and it seems that it is currently working for me.

**Comment by rsapko** [comment]
> > > I don't know, the problem for me it seems that the extension is not attaching to the packager and thus, cannot debug any breakpoints either on MAC or PC (I work on both)
> > 
> > 
> > Have you been able to find a setup that works with breakpoints in VSCODE? Attaching to Hermes works somewhat, but the source maps seem off and the 'watch' and 'variables' are inconsistent. Can you share a launch.json if you have it working?
> 
> @rsapko I have the React Native Tools extension and it seems that it is currently working for me. I wanted to try out Expo Tools because it is actually faster than the other one, but it's not working for me either right now.

@nicolasWD I have the React Native Tools Extension also. I've tried to get that to work too. Would you mind sharing your launch.json file with me. I need the configuration that works and I've tried everything.

**Comment by alexwolf22** [comment]
Hi I'm having the same issue.

i can't connect my debugger in vs code or the breakpoints set in the chrome dev tools javascript inspector. The only way to get to code to stop is by using hardcoded `debugger;` statements.

I'm using expo sdk `50.0.8`.

Have latest version of vscode and expo tools vs code plugin installed.

The hermes expo docs says
```
Test debugging availability by running the command: curl http://127.0.0.1:8081/json/list (adjust the 127.0.0.1:8081 to match your dev server URL). The HTTP response should be an array, as shown below. If it is an empty response, add either the --localhost or --tunnel flag to the npx expo start command.
```
I'm successfully getting an output here, so unsure what the issue is.

❯ curl http://127.0.0.1:8081/json/list
[
  {
    "id": "701e6363c14647968f3e69a5c3f0af5afe77b995-16",
    "description": "com.scratchodds.app",
    "title": "Hermes React Native",
    "faviconUrl": "https://reactjs.org/favicon.ico",
    "devtoolsFrontendUrl": "devtools://devtools/bundled/js_app.html?experiments=true&v8only=true&ws=192.168.1.77%3A8081%2Finspector%2Fdebug%3Fdevice%3D701e6363c14647968f3e69a5c3f0af5afe77b995%26page%3D16",
    "type": "node",
    "webSocketDebuggerUrl": "ws://192.168.1.77:8081/inspector/debug?device=701e6363c14647968f3e69a5c3f0af5afe77b995&page=16",
    "vm": "Hermes",
    "deviceName": "iPhone SE (3rd generation)"
  },
  {
    "id": "701e6363c14647968f3e69a5c3f0af5afe77b995--1",
    "description": "com.scratchodds.app",
    "title": "React Native Experimental (Improved Chrome Reloads)",
    "faviconUrl": "https://reactjs.org/favicon.ico",
    "devtoolsFrontendUrl": "devtools://devtools/bundled/js_app.html?experiments=true&v8only=true&ws=192.168.1.77%3A8081%2Finspector%2Fdebug%3Fdevice%3D701e6363c14647968f3e69a5c3f0af5afe77b995%26page%3D-1",
    "type": "node",
    "webSocketDebuggerUrl": "ws://192.168.1.77:8081/inspector/debug?device=701e6363c14647968f3e69a5c3f0af5afe77b995&page=-1",
    "vm": "don't use",
    "deviceName": "iPhone SE (3rd generation)"
  }
]

has anyone found a workaround? This a is a new react native project, and my productivity not using an IDE debugger is significantly lower.

**Comment by alexwolf22** [comment]
HI I've been able to get vs code debugger work for my dev client build on my simulator using.

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug React Native App",
      "request": "attach",
      "type": "reactnativedirect",
      "cwd": "${workspaceFolder}",
      "sourceMaps": true
    }
  ]
}

```

Posted abotu it in reaact native tools lib [here](https://github.com/microsoft/vscode-react-native/issues/2115) and got the solution.

Expo tools debugger still is not working, but using react native tools works.

**Comment by rsapko** [comment]
> HI I've been able to get vs code debugger work for my dev client build on my simulator using.
> 
> ```
> {
>   "version": "0.2.0",
>   "configurations": [
>     {
>       "name": "Debug React Native App",
>       "request": "attach",
>       "type": "reactnativedirect",
>       "cwd": "${workspaceFolder}",
>       "sourceMaps": true
>     }
>   ]
> }
> ```
> 
> Posted abotu it in reaact native tools lib [here](https://github.com/microsoft/vscode-react-native/issues/2115) and got the solution.
> 
> Expo tools debugger still is not working, but using react native tools works.

@alexwolf22 With Expo 50?

**Comment by rsapko** [comment]
@alexwolf22 Ah, I see...dev client build. I haven't switched from Expo Go yet. I think it's time. I'll have to figure that out now too.

**Comment by mccoyg** [comment]
I am working with the default stickersmash repo just to see if it works in general, not in my projects anymore after weeks of trying to get this working.

**Comment by ShimHyesu** [comment]
I have same problem. 
Expo SDK 49, VS Code v.1.87.0 and Expo Go v.2.29.6

**Comment by byCedric** [comment]
Hi all! Sorry for the inactivity here. We've published a new version, `1.3.0,` which should reinstate the debugging capabilities. It was caused by a change in vscode, and was affected by a bug that was fixed in vscode `1.86.0`. See PR #245 for more info. 

As a follow-up, we updated all our test fixtures to also ensure SDK 50 (and future SDK versions) are working as intended. And we will expand the existing tests, where possible.

I'll keep this issue open for now, but with `1.3.0`, you should be able to debug through vscode again.

---

Note that if vscode still gives you problems, you can also use the built-in Chrome DevTools. You can open this by pressing `j` in the terminal, after running `expo start`. The infrastructure behind this and vscode debugging are identical. But, there are some differences in how it works through vscode and Chrome DevTools.

**Comment by byCedric** [comment]
@rsapko Of course. Keep in mind that Expo Tools only supports debugging through Hermes, not through the "classic application" methods React Native Tools provides.

In short:
- **Expo Tools only supports Hermes apps**
  _React Native Tools calls this "Hermes: direct mode" -- but it's not an official name._
- **Expo Tools supports emulators, simulators, and actual devices**
  The emulator, simulator, or device just needs to run your app locally in development mode ._(it needs to be connected to Metro)_
- **Expo Tools has a "quick start" command to debug**
  This launches a new debug instance using the default settings, `127.0.0.1` / `8081` / etc. _The full command name is **Debug Expo app on a device or simulator, using Hermes**, command id is `expo.debug.start`_
- **Expo Tools allows you to select the target to inspect when multiple devices are connected**
  This will be visible as a vscode item picker modal, and shows you the device name. This applies to both the quickstart command, and the vscode launch config. _Keep in mind that if you use multiple simulators with the same name, it will be hard to pick the right device._

An example **.vscode/launch.json** would look something like:
```jsonc
{
  "configurations": [
    // Default settings generated from "Expo: Debug app on device or emulator"
    {
      "type": "expo",
      "request": "attach",
      "name": "Debug Expo app",
      "projectRoot": "${workspaceFolder}",
      "bundlerPort": "8081",
      "bundlerHost": "127.0.0.1"
    },
    // Slightly customized version
    {
      "type": "expo",
      "request": "attach",
      // Slightly different name
      "name": "Debug my-app",
      // When using monorepos, you have to specify the expo project path
      "projectRoot": "${workspaceFolder}/apps/my-app",
      // These can be modified however you want
      "bundlerPort": "8081",
      // localhost or your LAN address should also work fine
      "bundlerHost": "127.0.0.1",
      // Enable trace logs to debug the debugger :) (it contains the CDP communications between vscode and the app)
      "trace": true,
      // You can disable something called "turbo source maps", it's a semi-experimental feature from vscode
      // and should only be disabled if you are running into source maps or breakpoint binding issues
      "enableTurboSourcemaps": false,
    }
  ]
}
```

**Comment by rsapko** [comment]
@byCedric Thank you. I'll give it a try.

**Comment by ArnieGA** [comment]
@byCedric I'm afraid it is still not working on my end.
- Tried via `F1 > Expo: Debug Expo app on a device or simulator, using Hermes`.
- Tried via `launch.json` file using your example(s).
- Tried using `localhost`, `127.0.0.1` and then with my LAN IP as `bundlerHost` values.

What happens?
- Breakpoints **are not hit**.
- When debugger is stopped, breakpoints are shown in red in the editor, as they're supposed to, but not when debugger is running.
- Debugger only stops on `debugger` statements. However when it does, a new file tab is opened which doesn't include the `debugger` statement, and the debugger stops in the line right after the `debugger;` statement is in the original file. So in other words, 2 versions of the file exist:  the original one with the `debugger` statement, and a second one that is automatically opened (which doesn't include the `debugger` statement) and appears to be the one that handles the debugging in memory.

**Comment by byCedric** [comment]
@ArnieGA It sounds like you are running into source map issues, which are also preventing the debugger from binding breakpoints. Right now, Hermes doesn't support setting breakpoints by URI, so we have to fall back to source map-based bindings. This will be improved in later React Native versions.

If you want, you can share a repro with the project, with comments above the breakpoint locations you are trying to bind, I'm happy to take a look and see what we can do to improve.

Alternatively, as mentioned before, you can still use the Chrome DevTools which should be slightly better in terms of breakpoint binding. Keep in mind that not everything is bindable, like JSX elements in render functions.

**Comment by ArnieGA** [comment]
Thank you for clarifying that for me. :)

**Comment by byCedric** [comment]
Hi all! A quick follow-up on this issue:

- **We've expanded the tests and added unit and e2e tests**
  This includes tests around the interactions with Metro (fetching available devices) [here](https://github.com/expo/vscode-expo/tree/main/src/expo/__tests__), as well as starting up a debugging session and validating it has been started correctly ([here](https://github.com/expo/vscode-expo/blob/main/src/__tests__/expoDebuggers.e2e.ts)).
- **We've included `insiders`, or beta, vscode versions in tests**
  On every change, we now test vscode's "oldest supported version", "stable version", and "insiders" [here](https://github.com/expo/vscode-expo/pull/253). The tests are also tested on linux, macos, _and_ windows. Having the insiders tested too should give us a heads up whenever vscode changes behavior again (as mentioned in #245)
- **We've done a couple of quality of life improvements and other refactors since `1.3.0`**
- **More [debugging related information can be found here](https://github.com/expo/vscode-expo/issues/240#issuecomment-1983901129)**

For now, I'll close (and lock) this issue. If you are having trouble with breakpoints not binding, I'd love to hear about it. [As mentioned here](https://github.com/expo/vscode-expo/issues/240#issuecomment-1985958348), please open a new issue with a repro and the breakpoints you are trying to bind. I'd be more than happy to take a look and see what we can do to improve it.

Also, if I'm unresponsive on GitHub that's because I have 5k+ messages. You can always reach out on Twitter to me: https://twitter.com/cedric_dev.

Hope this helps!
